name: CI

on:
  pull_request:
    branches: ['*']

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        java:
          - adopt@1.8
#          - graalvm-ce-java11@20.3.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: cache-v1-${{ hashFiles('build.sbt') }}
          restore-keys: |
            cache-v1-
      - name: Compile and Test
        run: sbt +test